
title:  welcome is my web site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  description: >-
  **Soy [Tu Nombre], un apasionado ingeniero de software especializado en [Área de especialización].** Con una sólida base en [Tecnologías clave], he desarrollado soluciones innovadoras para [Problemas que has resuelto]. 
  
  En esta presentación, te llevaré a un recorrido por mis proyectos más destacados, como [Proyecto 1] y [Proyecto 2]. Descubrirás cómo he utilizado [Tecnologías específicas] para crear aplicaciones que [Beneficios de tus proyectos]. 

  **¿Quieres saber cómo la ingeniería de software puede transformar tu negocio?** ¡No te pierdas esta presentación!

baseurl: "/myNewSite/" # the subpath of your site, e.g. /blog
url: "https://candeh02.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


theme: minima
plugins:
  - jekyll-feed

