
title:  Mi primer bloc
email: your-email@example.com
description: >
  
  Soy CANDE HUAMAN CARRION, un apasionado ingeniero de software especializado en Desarrollo de software, Con una sólida base en Tecnologias, he desarrollado soluciones innovadoras para negocios. 
  

  ¿Quieres saber cómo la ingeniería de software puede transformar tu negocio? ¡Contactame por mis redes sociales!

baseurl: "/myNewSite/" 
url: "https://candeh02.github.io" 
linkedin_url: https://www.linkedin.com/in/candehuaman/
whatsapp_number: +5511912345678 


theme: minima
plugins:
  - jekyll-feed

